In [33]:
from tensorflow.keras.preprocessing.text import one_hot

In [34]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [35]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [36]:
##Define the vocabulary size
voc_size=10000

In [37]:
##One hot representation
one_hot_repr=[(one_hot(words,voc_size))for words in sent]

In [38]:
one_hot_repr

[[4651, 4744, 399, 4797],
 [4651, 4744, 399, 7920],
 [4651, 9442, 399, 5839],
 [2603, 6693, 2027, 8548, 8017],
 [2603, 6693, 2027, 8548, 139],
 [1374, 4651, 7505, 399, 8086],
 [8664, 1162, 2424, 8548]]

In [39]:
##word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [40]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs) 

[[   0    0    0    0 4651 4744  399 4797]
 [   0    0    0    0 4651 4744  399 7920]
 [   0    0    0    0 4651 9442  399 5839]
 [   0    0    0 2603 6693 2027 8548 8017]
 [   0    0    0 2603 6693 2027 8548  139]
 [   0    0    0 1374 4651 7505  399 8086]
 [   0    0    0    0 8664 1162 2424 8548]]


In [ ]:
## feature representation
dim=10

In [42]:

model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [43]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
embedded_docs

array([[   0,    0,    0,    0, 4651, 4744,  399, 4797],
       [   0,    0,    0,    0, 4651, 4744,  399, 7920],
       [   0,    0,    0,    0, 4651, 9442,  399, 5839],
       [   0,    0,    0, 2603, 6693, 2027, 8548, 8017],
       [   0,    0,    0, 2603, 6693, 2027, 8548,  139],
       [   0,    0,    0, 1374, 4651, 7505,  399, 8086],
       [   0,    0,    0,    0, 8664, 1162, 2424, 8548]], dtype=int32)

In [50]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[[-4.83862162e-02,  1.96038559e-03,  3.40183713e-02,
         -2.53869183e-02, -4.46171053e-02, -7.28732347e-03,
          4.06371690e-02, -3.03755403e-02, -1.96182728e-02,
          3.53601314e-02],
        [-4.83862162e-02,  1.96038559e-03,  3.40183713e-02,
         -2.53869183e-02, -4.46171053e-02, -7.28732347e-03,
          4.06371690e-02, -3.03755403e-02, -1.96182728e-02,
          3.53601314e-02],
        [-4.83862162e-02,  1.96038559e-03,  3.40183713e-02,
         -2.53869183e-02, -4.46171053e-02, -7.28732347e-03,
          4.06371690e-02, -3.03755403e-02, -1.96182728e-02,
          3.53601314e-02],
        [-4.83862162e-02,  1.96038559e-03,  3.40183713e-02,
         -2.53869183e-02, -4.46171053e-02, -7.28732347e-03,
          4.06371690e-02, -3.03755403e-02, -1.96182728e-02,
          3.53601314e-02],
        [ 1.63314603e-02,  1.64057277e-02, -4.11503799e-02,
         -8.88780504e-03, -3.79373431e-02,  4.51525562e-02,
          1.89614780e-02, -9.72859561e-05,  3.263379